project:
  type: website
  output-dir: _site

website:
  title: "gh zuo"
  description: "天津工业大学本科生"
  
  navbar:
    left:
      - href: index.qmd
        text: 首页 (Home)
      - href: research.qmd
        text: 研究 (Research)
      - href: publications.qmd
        text: 出版物 (Publications)
      - href: about.qmd
        text: 关于我 (About)
    
    right:
      - icon: envelope-fill
        href: "mailto:2311640319@tiangong.edu.cn"
        aria-label: Email
      - icon: mortarboard-fill
        href: "#" 
        aria-label: Google Scholar
      - icon: github
        href: "https://github.com/messizhh"
        aria-label: GitHub
  
  page-footer:
    left: "© 2025, gh zuo."
    center: "由 Quarto 驱动"
    right:
      - icon: github
        href: "https://github.com/messizhh"

format:
  html:
    theme:
      light: cosmo 
      dark: darkly
    css: styles.css